Task: null
TrainingFraction: null
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
all_joints_names:
- pupil 0
- pupil 45
- pupil 90
- pupil 135
- pupil 180
- pupil 225
- pupil 270
- pupil 315
- eyelid top
- eyelid bot
alphavalue: null
batch_size: 1
bodyparts: null
bottomheight: 400
colormap: null
corner2move2: null
crop: true
croppedtraining: null
cropping: null
cropratio: 0.4
dataset: training-datasets\iteration-1\UnaugmentedDataSet_eyeDb_behavioural_analysisSep1\eyeDb_behavioural_analysis_AT95shuffle1.mat
dataset_type: imgaug
date: null
default_augmenter: null
default_net_type: null
display_iters: 1000
dotsize: null
global_scale: 0.8
init_weights: C:\Users\experiment\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
iteration: null
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets\iteration-1\UnaugmentedDataSet_eyeDb_behavioural_analysisSep1\Documentation_data-eyeDb_behavioural_analysis_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
move2corner: null
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
multianimalproject: null
net_type: resnet_50
num_joints: 10
numframes2pick: null
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pcutoff: null
pos_dist_thresh: 17
project_path: D:\eyeDb_behavioural_analysis-AT-2020-09-01
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
scorer: null
skeleton: []
skeleton_color: black
snapshotindex: null
start: null
stop: null
topheight: 400
video_sets: null
x1: null
x2: null
y1: null
y2: null
